@extends('layouts.app')
@section('title','Apex Privé — The Luxury Marketplace')
@section('content')
<section class="lux-hero"><div class="lux-hero-copy"><p class="eyebrow">The private collection · 2026</p><h1>Objects of<br><em>distinction.</em></h1><p>Exceptional fashion, watches, jewelry, beauty and design from the world's most revered maisons.</p><div><a class="button luxury-button" href="#collection">Discover the edit</a><a class="quiet-link" href="{{route('brands.index')}}">Explore 100+ maisons →</a></div></div><div class="lux-visual"><div class="lux-frame"><span>APEX PRIVÉ</span><small>CURATED GLOBALLY</small></div></div></section>
<section class="lux-promises"><div><b>01</b><span><strong>Authenticated</strong><small>Every piece, guaranteed</small></span></div><div><b>02</b><span><strong>White-glove delivery</strong><small>Handled with exceptional care</small></span></div><div><b>03</b><span><strong>Private client service</strong><small>Advisors available worldwide</small></span></div></section>
<section class="brand-marquee"><p>Featured maisons</p><div>@foreach($featuredBrands as $brand)<span>{{$brand->name}}</span>@endforeach</div><a href="{{route('brands.index')}}">View all designers</a></section>
<section class="lux-departments"><div class="section-title"><div><p class="eyebrow">Curated worlds</p><h2>Shop by department</h2></div></div><div class="department-grid"><a href="{{route('brands.index',['niche'=>'Fashion Houses'])}}"><b>01</b><h3>Fashion</h3><p>Icons of the runway</p></a><a href="{{route('brands.index',['niche'=>'Watches'])}}"><b>02</b><h3>Watches</h3><p>Masters of time</p></a><a href="{{route('brands.index',['niche'=>'Jewelry'])}}"><b>03</b><h3>Fine jewelry</h3><p>Rare brilliance</p></a><a href="{{route('brands.index',['niche'=>'Home & Design'])}}"><b>04</b><h3>Home &amp; design</h3><p>Collectible living</p></a></div></section>
<section class="shop luxury-shop" id="collection"><div class="section-title"><div><p class="eyebrow">The new selection</p><h2>Pieces worth knowing</h2></div><p>{{$products->total()}} curated pieces</p></div><form class="filters"><input name="search" value="{{request('search')}}" placeholder="Search the collection…"><x-ui.select name="category" aria-label="Department"><option value="">All departments</option>@foreach($categories as $category)<option value="{{$category->slug}}" @selected(request('category')===$category->slug)>{{$category->name}}</option>@endforeach</x-ui.select><x-ui.select name="sort" aria-label="Sort collection"><option value="">Curator's order</option><option value="price-low" @selected(request('sort')==='price-low')>Price: low to high</option><option value="price-high" @selected(request('sort')==='price-high')>Price: high to low</option></x-ui.select><button>Refine</button></form><div class="grid">@forelse($products as $product)@include('store._card',['product'=>$product])@empty<div class="empty"><h3>No pieces found</h3><p>Adjust your selection to continue exploring.</p></div>@endforelse</div><div class="pagination">{{$products->links()}}</div></section>
<section class="editorial-banner"><p class="eyebrow">The Apex Journal</p><h2>The art of collecting well.</h2><p>Stories of craft, provenance and enduring design.</p><a href="{{route('brands.index')}}">Meet the maisons →</a></section>
@endsection
